steemit/devportal-tutorials-js

tutorials/03_client_signing/README.md, tutorials/03_client_signing/index.js, tutorials/03_client_signing/package-lock.json, tutorials/03_client_signing/package.json, tutorials/03_client_signing/public/app.js, tutorials/03_client_signing/public/index.html, tutorials/03_client_signing/public/style.scss, tutorials/03_client_signing/webpack.config.js
Closes #6 
Initial release of client signing tutorial
README is included that will resolve #8 as well
=> Client signing tutorial

README.md
=> Update readme with latest tutorial list

tutorials/01_blog_feed/README.md, tutorials/01_blog_feed/package-lock.json, tutorials/01_blog_feed/public/app.js
=> Fix bugs and readme

package.json, tutorials/04_get_posts/README.md, tutorials/04_get_posts/index.js, tutorials/04_get_posts/package-lock.json, tutorials/04_get_posts/package.json, tutorials/04_get_posts/public/app.js, tutorials/04_get_posts/public/index.html, tutorials/04_get_posts/public/style.scss, tutorials/04_get_posts/webpack.config.js
=> 04 Tutorial Get posts

tutorials/05_get_post_details/README.md, tutorials/05_get_post_details/index.js, tutorials/05_get_post_details/package-lock.json, tutorials/05_get_post_details/package.json, tutorials/05_get_post_details/public/app.js, tutorials/05_get_post_details/public/index.css, tutorials/05_get_post_details/public/index.html, tutorials/05_get_post_details/public/style.scss, tutorials/05_get_post_details/webpack.config.js
=> 05 Tutorial Get content details

tutorials/04_get_posts/README.md
=> Replace 'category' with 'tag' +minor lang corrections #56

README.md, tutorials/01_blog_feed/README.md, tutorials/01_blog_feed/package-lock.json, tutorials/01_blog_feed/package.json, tutorials/02_steemconnect/README.md, tutorials/02_steemconnect/package-lock.json, tutorials/02_steemconnect/package.json, tutorials/03_client_signing/README.md, tutorials/03_client_signing/package-lock.json, tutorials/03_client_signing/package.json, tutorials/04_get_posts/README.md, tutorials/04_get_posts/package-lock.json, tutorials/04_get_posts/package.json, tutorials/05_get_post_details/README.md, tutorials/05_get_post_details/package-lock.json, tutorials/05_get_post_details/package.json
=> 54 use webpack dev server in all existing examples

README.md
=> Tutorial list update

tutorials/08_get_account_replies/README.md, tutorials/08_get_account_replies/index.js, tutorials/08_get_account_replies/package-lock.json, tutorials/08_get_account_replies/package.json, tutorials/08_get_account_replies/public/app.js, tutorials/08_get_account_replies/public/index.css, tutorials/08_get_account_replies/public/index.html, tutorials/08_get_account_replies/public/style.scss, tutorials/08_get_account_replies/webpack.config.js
=> JS-T: Get account replies

tutorials/06_get_voters_list_on_post/README.md, tutorials/06_get_voters_list_on_post/index.js, tutorials/06_get_voters_list_on_post/package-lock.json, tutorials/06_get_voters_list_on_post/package.json, tutorials/06_get_voters_list_on_post/public/app.js, tutorials/06_get_voters_list_on_post/public/index.css, tutorials/06_get_voters_list_on_post/public/index.html, tutorials/06_get_voters_list_on_post/public/style.scss, tutorials/06_get_voters_list_on_post/webpack.config.js
Need to confirm my interpretation of results
=> Resolves #18

tutorials/10_submit_post/README.md, tutorials/10_submit_post/index.js, tutorials/10_submit_post/package-lock.json, tutorials/10_submit_post/package.json, tutorials/10_submit_post/public/app.js, tutorials/10_submit_post/public/index.html, tutorials/10_submit_post/public/style.scss, tutorials/10_submit_post/webpack.config.js
=> JS-T: Submit post

tutorials/06_get_voters_list_on_post/README.md, tutorials/06_get_voters_list_on_post/package-lock.json, tutorials/06_get_voters_list_on_post/package.json, tutorials/09_get_account_comments/README.md, tutorials/09_get_account_comments/index.js, tutorials/09_get_account_comments/package-lock.json, tutorials/09_get_account_comments/package.json, tutorials/09_get_account_comments/public/app.js, tutorials/09_get_account_comments/public/index.css, tutorials/09_get_account_comments/public/index.html, tutorials/09_get_account_comments/public/style.scss, tutorials/09_get_account_comments/webpack.config.js
=> JS_T: Get account comments

README.md, tutorials/README.md, tutorials/tutorial_structure.md
=> Add README.md guidlines for all tutorials #74

package.json
=> prettier pre-commit hook to only check modified files #76

tutorials/13_stream_blockchain_transactions/README.md, tutorials/13_stream_blockchain_transactions/index.js, tutorials/13_stream_blockchain_transactions/package-lock.json, tutorials/13_stream_blockchain_transactions/package.json, tutorials/13_stream_blockchain_transactions/public/app.js, tutorials/13_stream_blockchain_transactions/public/index.html, tutorials/13_stream_blockchain_transactions/public/style.scss, tutorials/13_stream_blockchain_transactions/webpack.config.js
=> JS-T: Stream transactions

README.md
=> Update readme, fix TOC

tutorials/00_getting_started/README.md
=> JS-T: Getting started

tutorials/00_getting_started/README.md, tutorials/04_get_posts/README.md
=> fixed links #99

tutorials/21_claim_rewards/README.md, tutorials/21_claim_rewards/index.js, tutorials/21_claim_rewards/package-lock.json, tutorials/21_claim_rewards/package.json, tutorials/21_claim_rewards/public/app.js, tutorials/21_claim_rewards/public/index.css, tutorials/21_claim_rewards/public/index.html, tutorials/21_claim_rewards/public/style.scss, tutorials/21_claim_rewards/webpack.config.js
=> JS-T: Claim rewards

tutorials/24_create_account/README.md, tutorials/24_create_account/index.js, tutorials/24_create_account/package-lock.json, tutorials/24_create_account/package.json, tutorials/24_create_account/public/app.js, tutorials/24_create_account/public/index.css, tutorials/24_create_account/public/index.html, tutorials/24_create_account/public/style.scss, tutorials/24_create_account/webpack.config.js
=> JS-T: Create an account

tutorials/23_power_down/README.md, tutorials/23_power_down/index.js, tutorials/23_power_down/package-lock.json, tutorials/23_power_down/package.json, tutorials/23_power_down/public/app.js, tutorials/23_power_down/public/index.css, tutorials/23_power_down/public/index.html, tutorials/23_power_down/public/style.scss, tutorials/23_power_down/webpack.config.js
=> JS-T: Power down vests

tutorials/22_power_up_steem/README.md, tutorials/22_power_up_steem/index.js, tutorials/22_power_up_steem/package-lock.json, tutorials/22_power_up_steem/package.json, tutorials/22_power_up_steem/public/app.js, tutorials/22_power_up_steem/public/index.css, tutorials/22_power_up_steem/public/index.html, tutorials/22_power_up_steem/public/style.scss, tutorials/22_power_up_steem/webpack.config.js
=> JS-T: Power up STEEM

tutorials/10_submit_post/README.md, tutorials/11_submit_comment_reply/README.md, tutorials/12_edit_content_patching/README.md, tutorials/14_reblogging_post/README.md
=> update readme with broadcast op ref

tutorials/18_follow_another_user/README.md, tutorials/18_follow_another_user/index.js, tutorials/18_follow_another_user/package.json, tutorials/18_follow_another_user/public/app.js, tutorials/18_follow_another_user/public/index.html, tutorials/18_follow_another_user/public/style.scss, tutorials/18_follow_another_user/webpack.config.js
=> 30 follow another user

tutorials/19_get_follower_and_following_list/README.md, tutorials/19_get_follower_and_following_list/index.js, tutorials/19_get_follower_and_following_list/package.json, tutorials/19_get_follower_and_following_list/public/app.js, tutorials/19_get_follower_and_following_list/public/index.html, tutorials/19_get_follower_and_following_list/public/style.scss, tutorials/19_get_follower_and_following_list/webpack.config.js
=> 29 get follower and following list

tutorials/25_delegate_power/README.md, tutorials/25_delegate_power/index.js, tutorials/25_delegate_power/package.json, tutorials/25_delegate_power/public/app.js, tutorials/25_delegate_power/public/index.css, tutorials/25_delegate_power/public/index.html, tutorials/25_delegate_power/public/style.scss, tutorials/25_delegate_power/webpack.config.js
=> JS-T: Delegate power

tutorials/26_set_withdraw_route/README.md, tutorials/26_set_withdraw_route/index.js, tutorials/26_set_withdraw_route/package-lock.json, tutorials/26_set_withdraw_route/package.json, tutorials/26_set_withdraw_route/public/app.js, tutorials/26_set_withdraw_route/public/index.css, tutorials/26_set_withdraw_route/public/index.html, tutorials/26_set_withdraw_route/public/style.scss, tutorials/26_set_withdraw_route/webpack.config.js
=> JS-T: Set withdraw route

tutorials/14_reblogging_post/README.md, tutorials/15_search_accounts/README.md, tutorials/16_search_tags/README.md
=> 107 fix terminology in js t

tutorials/21_witness_listing_and_voting/README.md, tutorials/21_witness_listing_and_voting/index.js, tutorials/21_witness_listing_and_voting/package.json, tutorials/21_witness_listing_and_voting/public/app.js, tutorials/21_witness_listing_and_voting/public/index.html, tutorials/21_witness_listing_and_voting/public/style.scss, tutorials/21_witness_listing_and_voting/webpack.config.js
=> 38 witness listing and voting

tutorials/27_get_delegations_by_user/README.md, tutorials/27_get_delegations_by_user/index.js, tutorials/27_get_delegations_by_user/package.json, tutorials/27_get_delegations_by_user/public/app.js, tutorials/27_get_delegations_by_user/public/index.html, tutorials/27_get_delegations_by_user/public/style.scss, tutorials/27_get_delegations_by_user/webpack.config.js
=> 40 get delegations by user

tutorials/28_grant_posting_permission/README.md, tutorials/28_grant_posting_permission/index.js, tutorials/28_grant_posting_permission/package.json, tutorials/28_grant_posting_permission/public/app.js, tutorials/28_grant_posting_permission/public/index.html, tutorials/28_grant_posting_permission/public/style.scss, tutorials/28_grant_posting_permission/webpack.config.js
=> 41 grant posting permission to another account

tutorials/01_blog_feed/public/app.js, tutorials/03_client_signing/public/app.js, tutorials/03_client_signing/public/index.html, tutorials/10_submit_post/public/app.js, tutorials/11_submit_comment_reply/public/app.js, tutorials/12_edit_content_patching/public/app.js, tutorials/17_vote_on_content/README.md, tutorials/17_vote_on_content/public/app.js, tutorials/18_follow_a_user/README.md, tutorials/18_follow_a_user/public/app.js, tutorials/21_transfer_steem_and_sbd/public/app.js, tutorials/22_witness_listing_and_voting/README.md, tutorials/22_witness_listing_and_voting/public/app.js, tutorials/configuration.js
=> 112 central net configuration fixed

tutorials/11_submit_comment_reply/README.md
=> upd readme of tut 11_submit_comment_reply with HF20 changes

tutorials/32_convert_sbd_to_steem/README.md, tutorials/32_convert_sbd_to_steem/index.js, tutorials/32_convert_sbd_to_steem/package.json, tutorials/32_convert_sbd_to_steem/public/app.js, tutorials/32_convert_sbd_to_steem/public/index.html, tutorials/32_convert_sbd_to_steem/public/style.scss, tutorials/32_convert_sbd_to_steem/webpack.config.js, tutorials/configuration.js
=> JS-T Convert SBD to STEEM #36

tutorials/27_delegate_power/README.md
=> Update 27_delegate_power readme #135

tutorials/26_create_account/README.md, tutorials/26_create_account/package.json, tutorials/26_create_account/public/app.js, tutorials/26_create_account/public/index.html
=> 134 update all account creation refs
